export enum ContentType {
    JSON = "application/json",
    HTML = "text/html",
    TEXT = "text/plain",
    XML = "application/xml",
    TEXT_XML = "text/xml",
    JAVASCRIPT = "application/javascript",
    CSS = "text/css",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    FORM_DATA = "multipart/form-data",
    PNG = "image/png",
    JPEG = "image/jpeg",
    GIF = "image/gif",
    BMP = "image/bmp",
    WEBP = "image/webp",
    SVG = "image/svg+xml",
    MP3 = "audio/mpeg",
    WAV = "audio/wav",
    MP4 = "video/mp4",
    MPEG = "video/mpeg",
    PDF = "application/pdf",
    ZIP = "application/zip",
    GZIP = "application/gzip"
}
